version: "3"
services:
  bootnode:
    image: domecloud/jfin-validator-node
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--networkid=3501"
      - "--nodekeyhex=633ab917d09441de38ae9251e79ced41df39a1c338842b826c18fb1773246e18"
      - "--syncmode=full"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./datadir/bootnode:/datadir/geth"
    ports:
      - "30303:30303"
    restart: always

  validator_1:
    image: domecloud/jfin-validator-node
    command:
      
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xe8391988483355e6a8170AC10f5726D4868e5C68"
      - "--miner.etherbase=0xe8391988483355e6a8170AC10f5726D4868e5C68"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@192.168.100.10:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=3501"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystore:/datadir/keystore"
      - "./password.txt:/datadir/password.txt"
      - "./datadir/validator_1:/datadir/geth"
    ports:
      - "40301:30303"
    restart: always
  validator_2:
    image: domecloud/jfin-validator-node
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x6DE767908d0d792385200E30d66A5696B24f709c"
      - "--miner.etherbase=0x6DE767908d0d792385200E30d66A5696B24f709c"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@192.168.100.10:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=3501"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystore:/datadir/keystore"
      - "./password.txt:/datadir/password.txt"
      - "./datadir/validator_2:/datadir/geth"
    ports:
      - "40302:30303"
    restart: always
  validator_3:
    image: domecloud/jfin-validator-node
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xa22fD0F35d2416eC293E2D00A8eB0c3Bc633Aa91"
      - "--miner.etherbase=0xa22fD0F35d2416eC293E2D00A8eB0c3Bc633Aa91"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@192.168.100.10:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=3501"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystore:/datadir/keystore"
      - "./password.txt:/datadir/password.txt"
      - "./datadir/validator_3:/datadir/geth"
    ports:
      - "40303:30303"
    restart: always

  validator_4:
    image: domecloud/jfin-validator-node
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xCd4A92A21539Fd2b50d1ecabce89cCf7294100C8"
      - "--miner.etherbase=0xCd4A92A21539Fd2b50d1ecabce89cCf7294100C8"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@192.168.100.10:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=3501"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystore:/datadir/keystore"
      - "./password.txt:/datadir/password.txt"
      - "./datadir/validator_4:/datadir/geth"
    ports:
      - "40305:30303"
    restart: always

  validator_5:
    image: domecloud/jfin-validator-node
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x88Cf3c2a965e2636155bCEf7264B805E8f57EF97"
      - "--miner.etherbase=0x88Cf3c2a965e2636155bCEf7264B805E8f57EF97"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@192.168.100.10:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=3501"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystore:/datadir/keystore"
      - "./password.txt:/datadir/password.txt"
      - "./datadir/validator_5:/datadir/geth"
    ports:
      - "40305:30303"
    restart: always

  rpc:
    image: domecloud/jfin-validator-node
    command:
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@192.168.100.10:30303"
      - "--networkid=3501"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,trace,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystore:/datadir/keystore"
      - "./password.txt:/datadir/password.txt"
      - "./datadir/rpc:/datadir/geth"
    restart: always

